; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = tc22_bench

[env_base]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize, esp32_exception_decoder
build_flags =
    -DCURRENT_FW_VERSION="\"1.0.1\""
lib_deps =
    ArduinoJson
    knolleary/PubSubClient @ 2.8
    HTTPClient
    WiFi
    adafruit/Adafruit GFX Library@^1.12.2
    adafruit/Adafruit ILI9341
    espressif/WROVER KIT LCD@^1.0.3

; ===== sensor modes =====
[env:fake]
extends = env_base
build_flags =
    ${env_base.build_flags}
    -DFAKE_MODE
    -DENABLE_MQTT_LOG=0
    -DUSE_BUTTON=0

[env:tf02_bench]
extends = env_base
build_flags =
    ${env_base.build_flags}
    -DUSE_TF02_PRO
    -DENABLE_MQTT_LOG=1
    -DUSE_BUTTON=0

[env:tf02_release]
extends = env_base
build_flags =
    ${env_base.build_flags}
    -DUSE_TF02_PRO
    -DENABLE_MQTT_LOG=0
    -DUSE_BUTTON=1

[env:tc22_bench]
extends = env_base
build_flags =
    ${env_base.build_flags}
    -DUSE_TC22
    -DENABLE_MQTT_LOG=1
    -DUSE_BUTTON=0
    -DMQTT_MAX_PACKET_SIZE=1024

[env:tc22_release]
extends = env_base
build_flags =
    ${env_base.build_flags}
    -DUSE_TC22
    -DENABLE_MQTT_LOG=0
    -DUSE_BUTTON=1
